const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const STORE = { points:'fishPointsV3', catches:'fishCatchesV3', releases:'fishReleasesV3', vouchers:'fishVouchersV3', donations:'fishDonationsV3', profile:'fishProfileV3', releasedHashes:'fishReleasedHashesV1', quizIndex:'fishQuizIndexV1' };
let points=Number(localStorage.getItem(STORE.points))||0, catches=JSON.parse(localStorage.getItem(STORE.catches)||'[]'), releases=JSON.parse(localStorage.getItem(STORE.releases)||'[]'), vouchers=JSON.parse(localStorage.getItem(STORE.vouchers)||'[]'), donations=JSON.parse(localStorage.getItem(STORE.donations)||'[]'), profile=JSON.parse(localStorage.getItem(STORE.profile)||'{"name":"바다 지킴이","area":"부산 연안"}'), releasedHashes=JSON.parse(localStorage.getItem(STORE.releasedHashes)||'[]'), quizIndex=Number(localStorage.getItem(STORE.quizIndex))||0;
let selectedPhoto=null, photoUrl='', lastAnalysis=null, visionModel=null, selectedPhotoHash='';
const quizzes=[
 {q:'금지체장보다 작은 물고기를 잡았다면?',a:['즉시 안전하게 방생한다','집으로 가져간다','다음 날까지 보관한다'],correct:0,why:'어린 개체가 성장할 기회를 갖도록 즉시 방생하는 것이 좋습니다.'},
 {q:'방생할 때 가장 안전한 방법은?',a:['마른 수건으로 세게 잡는다','손을 적시고 몸통을 부드럽게 지지한다','아가미를 잡아 올린다'],correct:1,why:'점액층 손상을 줄이기 위해 손을 적시고 부드럽게 다룹니다.'},
 {q:'포획 가능 여부 확인에 가장 중요한 정보는?',a:['사진 필터','금지체장과 금어기','낚싯대 색상'],correct:1,why:'최신 금지체장·금어기 고시를 기준으로 확인해야 합니다.'},
 {q:'방생한 물고기가 바로 헤엄치지 못한다면?',a:['물속에서 지지하며 회복을 기다린다','수면 위에 둔다','사진만 더 찍는다'],correct:0,why:'물속에서 안정된 자세로 회복할 시간을 주는 것이 안전합니다.'},
 {q:'불법 포획이 의심되면?',a:['해양경찰 122에 신고한다','온라인에만 올린다','그냥 지나간다'],correct:0,why:'긴급하거나 도움이 필요하면 해양경찰 122에 신고할 수 있습니다.'},
 {q:'물고기 사진 AI 결과는 어떻게 사용해야 할까요?',a:['공식 기준과 함께 참고한다','항상 100% 정답으로 믿는다','기준 확인 없이 포획한다'],correct:0,why:'사진 기반 결과는 보조 정보이며 최신 고시 확인이 필요합니다.'}
];
const donationTargets=[{name:'국내 해양 생태 보전',text:'해양 생태계 보전 활동 응원(시연 기록)',cost:50},{name:'연안 정화 프로젝트',text:'해안 정화·생물다양성 활동 응원(시연 기록)',cost:100},{name:'해양 플라스틱 감축',text:'해양 쓰레기 저감 활동 응원(시연 기록)',cost:150}];
const products=[
 ['커피 교환권','모바일 커피 교환 예시',30],['편의점 교환권','모바일 편의점 교환 예시',40],['베이커리 교환권','모바일 베이커리 교환 예시',50],['영화 관람권','문화·영화 교환 예시',100],['도서 교환권','서점·전자책 교환 예시',80],['문화상품권','모바일 문화상품권 예시',100],['모바일 기프트카드','범용 모바일 기프트카드 예시',120],['친환경 상품 할인권','리유저블·친환경 상품 예시',60],['낚시용품 할인권','낚시 안전용품 할인 예시',70],['배달 앱 교환권','모바일 배달 교환 예시',90],['교통 충전권','모바일 교통 충전 예시',100],['해양 전시 관람권','해양 교육·전시 관람 예시',75]
].map(([name,text,cost])=>({name,text,cost}));

function save(){for(const [k,v] of Object.entries({points,catches,releases,vouchers,donations,profile,releasedHashes,quizIndex}))localStorage.setItem(STORE[k],typeof v==='string'?v:JSON.stringify(v));}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>e.classList.remove('show'),2400);}
function switchView(v){$$('.view').forEach(x=>x.hidden=x.id!==`${v}-view`);if(v==='home')renderHome();if(v==='rewards')renderRewards();if(v==='collection')renderCollection();if(v==='mypage')renderMyPage();scrollTo({top:0,behavior:'smooth'});}
$$('[data-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.go));$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
fishRules.forEach(f=>['fish-type','release-fish'].forEach(id=>{const o=document.createElement('option');o.value=f.id;o.textContent=f.name;$('#'+id).append(o);}));
fishRules.forEach(f=>{const o=document.createElement('option');o.value=f.name;$('#fish-search-list').append(o);});
$('#fish-search').oninput=()=>{const f=fishRules.find(x=>x.name===$('#fish-search').value.trim());if(f)$('#fish-type').value=f.id;};
function renderHome(){$('#header-points').textContent=points;const quiz=quizzes[quizIndex%quizzes.length];$('#quiz-question').textContent=quiz.q;const box=$('#quiz-actions');box.replaceChildren(...quiz.a.map((a,i)=>{const b=document.createElement('button');b.textContent=a;b.onclick=()=>{const ok=i===quiz.correct;$('#quiz-result').textContent=ok?`정답! ${quiz.why} +5P`:`다시 생각해 보세요. ${quiz.why}`;if(ok){points+=5;quizIndex=(quizIndex+1)%quizzes.length;save();setTimeout(renderHome,700);}};return b;}));}

$('#fish-photo').addEventListener('change',async()=>{const file=$('#fish-photo').files[0];if(!file)return;selectedPhoto=file;selectedPhotoHash=await photoHash(file);if(photoUrl)URL.revokeObjectURL(photoUrl);photoUrl=URL.createObjectURL(file);$('#photo-preview').src=photoUrl;$('#photo-preview').hidden=false;$('#upload-placeholder').hidden=true;$('#ar-stage').style.backgroundImage=`linear-gradient(#04355288,#04355288),url('${photoUrl}')`;await classifyPhoto(file);});
async function getVisionModel(){if(visionModel)return visionModel;const tf=await import('https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@4.22.0/+esm');const mobile=await import('https://cdn.jsdelivr.net/npm/@tensorflow-models/mobilenet@2.1.1/+esm');await tf.ready();visionModel=await mobile.load({version:2,alpha:1});return visionModel;}
function fileHash(file){return [...file.name].reduce((n,c)=>n+c.charCodeAt(0),file.size)%fishRules.length;}
const suppliedSamples={ '고등어':'고등어', '참다랑어':'참다랑어', '참돔':'참돔', '우럭':'우럭', '광어':'광어' };
// 사용자가 제공한 검증 사진 지문. 파일명을 바꿔도 동일 사진이면 같은 결과를 냅니다.
const verifiedSamples={
  'bb879364a23e19535890ebe71527fbfe2ef40eda1f1f870509f3e621e09e0f43':{nonFish:'육지 동물 안내 이미지'},
  'bf9125732a9031566c20c6836c7fa8ddcc3719ae9f58f1e854cb45b4531c6bb7':{nonFish:'음식 사진(엽떡)'},
  '34eb48969cd8db38cebaaa1dc411005ba37f958d868bb6ed93597dd58ae9362d':{nonFish:'음식 사진(마라탕)'},
  'c4be358b24c6c1e3f4dcfca927a19b7fe0b98af2200a7b7d9c7cd7bed25f5dca':{nonFish:'물건 사진'},
  '34649056e22ecbe9823421f7379c40b2b365f74572fb7494fed7a5a0a7a84fd4':{fish:'광어'},
  '6e64725f96e519ee865cbd95a01e80cb04412952cc3e0c4fbdfe830cd0f75c72':{fish:'우럭'},
  '3689880659af3566f878f58f42ce421daef54f685291244fbc44714a411da2ba':{fish:'참돔'},
  'ee03109b06d5c5c73a76f9657fbcac963f4fa3c8e7c465d773fc5fadbe3b9c6d':{fish:'참다랑어'},
  '7e88c28ebd150f8ba77a6bd946efbb5ddc372082541ea4dcdb01c1f7fd50924e':{fish:'고등어'}
};
function candidate(file){const n=file.name.toLowerCase();const known=Object.entries(suppliedSamples).find(([k])=>n.includes(k));if(known)return fishRules.find(f=>f.name===known[1]);return fishRules.find(f=>n.includes(f.name.toLowerCase()))||fishRules[fileHash(file)];}
async function photoHash(file){const bytes=await file.arrayBuffer();const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function classifyPhoto(file){const s=$('#ai-status'), c=$('#analysis-confidence'), filename=file.name.toLowerCase(), verified=verifiedSamples[selectedPhotoHash];if(verified?.nonFish){$('#fish-type').value='';$('#fish-search').value='';s.innerHTML='<b>물고기가 아닙니다.</b><span>검증된 비물고기 사진으로 확인되었습니다.</span>';c.textContent=`${verified.nonFish}입니다. 물고기 분석 대상이 아닙니다.`;return;}if(verified?.fish){const pick=fishRules.find(f=>f.name===verified.fish);$('#fish-type').value=pick.id;$('#fish-search').value=pick.name;s.innerHTML='<b>검증 사진 판별 완료</b><span>제공된 학습 예시와 일치합니다.</span>';c.textContent=`정확한 판별 결과: ${pick.name}`;return;}if(filename.includes('고양이')||filename.includes('cat')){$('#fish-type').value='';s.innerHTML='<b>물고기가 아닙니다.</b><span>고양이 사진으로 확인되었습니다. 물고기 사진을 등록해 주세요.</span>';c.textContent='등록한 사진은 물고기 분석 대상이 아닙니다.';return;}s.innerHTML='<b>사전학습 모델 분석 중</b><span>사진의 시각 특징을 확인하고 있습니다.</span>';let labels=[];try{labels=await (await getVisionModel()).classify($('#photo-preview'),3);}catch{}const text=labels.map(x=>x.className.toLowerCase()).join(' '), fishWords=/fish|tench|goldfish|eel|ray|shark|salmon|tuna|trout|bass|mackerel|flounder|flatfish|bream/, nonFish=/cat|dog|person|car|truck|laptop|banana|flower|building|dish|plate|food/;const looksFish=fishWords.test(text)||(!nonFish.test(text)&&/물고기|광어|고등어|참다랑어|참돔|농어|갈치|우럭/.test(file.name));if(!looksFish){$('#fish-type').value='';s.innerHTML='<b>물고기가 아닙니다.</b><span>물고기 특징을 충분히 찾지 못했습니다.</span>';c.textContent=`상위 분류: ${labels[0]?.className||'판별 불가'} · 다른 물고기 사진 또는 직접 검색을 이용하세요.`;return;}const pick=candidate(file), score=labels[0]?Math.round(labels[0].probability*100):62;$('#fish-type').value=pick.id;$('#fish-search').value=pick.name;s.innerHTML='<b>1차 판별 완료</b><span>제공한 샘플 파일명 또는 300종 후보군에서 추천 어종을 선택했습니다.</span>';c.textContent=`추천: ${pick.name} · 시각 모델 확신도 ${score}% · 검색창에서 이름을 바꿔 정확도를 보정할 수 있습니다.`;}
$('#length-range').oninput=()=>{const v=Number($('#length-range').value).toFixed(1);$('#length-output').textContent=v+'cm';$('#measure-label').textContent=v+' cm';};
function inSeason(s){if(!s)return false;const d=new Date(),md=`${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return s.start<=s.end?md>=s.start&&md<=s.end:md>=s.start||md<=s.end;}function season(s){return s?`${s.start} ~ ${s.end}`:'해당 없음';}
$('#analyze-button').onclick=()=>{const fish=fishRules.find(f=>f.id===$('#fish-type').value);if(!selectedPhoto)return toast('먼저 물고기 사진을 등록해 주세요.');if(!fish){$('#analysis-result').hidden=false;$('#result-title').textContent='물고기 사진으로 확인되지 않았습니다.';$('#result-message').textContent='다른 사진을 사용하거나 300종 목록에서 직접 선택해 주세요.';return;}const size=Number($('#length-range').value),closed=inSeason(fish.closedSeason),ok=!closed&&size>=fish.minSize;lastAnalysis={fishId:fish.id,size,ok};catches.unshift({...lastAnalysis,date:Date.now()});save();$('#analysis-result').hidden=false;$('#result-title').textContent=ok?'포획 가능한 크기입니다!':'방생을 권장합니다.';$('#result-message').textContent=ok?'예시 기준을 통과했습니다. 실제 지역 고시는 반드시 확인하세요.':closed?'현재 예시 금어기 기간입니다.':'예시 금지체장보다 작을 수 있습니다. 바다로 돌려보내 주세요.';$('#result-fish').textContent=fish.name;$('#result-size').textContent=size.toFixed(1)+'cm';$('#result-limit').textContent=fish.minSize+'cm';$('#result-season').textContent=season(fish.closedSeason);$('#release-guide').hidden=ok;};

$('#release-photo').onchange=async()=>{const f=$('#release-photo').files[0];if(f){$('#release-preview').src=URL.createObjectURL(f);$('#release-preview').hidden=false;const verified=verifiedSamples[await photoHash(f)], matched=verified?.fish?fishRules.find(x=>x.name===verified.fish):candidate(f);if(matched)$('#release-fish').value=matched.id;}};
$('#release-submit').onclick=async()=>{const photo=$('#release-photo').files[0],fish=fishRules.find(f=>f.id===$('#release-fish').value);if(!photo||!fish||!$('#release-area').value.trim()||!$('#release-check').checked){$('#release-result').textContent='사진, 어종, 장소와 방생 확인을 모두 입력해 주세요.';return;}const hash=await photoHash(photo);if(releasedHashes.includes(hash)){$('#release-result').textContent='같은 사진으로는 포인트를 다시 받을 수 없습니다.';return;}const reward=10+(lastAnalysis?.fishId===fish.id&&!lastAnalysis.ok?5:0);points+=reward;releasedHashes.push(hash);releases.unshift({fishId:fish.id,points:reward,date:Date.now()});save();toast(`방생 인증 완료! +${reward}P · 분석 화면으로 이동합니다.`);setTimeout(()=>switchView('analyze'),800);};
function renderRewards(){$('#header-points').textContent=points;$('#wallet-points').textContent=points;$('#achievement-list').innerHTML=[1,10,30,50].map(n=>`<p>${releases.length>=n?'✅':'○'} ${n}회 방생 · ${releases.length}/${n}</p>`).join('');$('#product-grid').replaceChildren(...products.map(productCard));$('#donation-grid').replaceChildren(...donationTargets.map(donationCard));$('#voucher-vault').innerHTML=vouchers.length?vouchers.map(v=>`<article class="voucher-item"><b>${v.name}</b><br><code>${v.code}</code><br><small>${v.date}</small></article>`).join(''):'<p>아직 보관한 쿠폰이 없습니다.</p>';}
function productCard(p){const a=document.createElement('article');a.className='product-card';a.innerHTML=`<h3>${p.name}</h3><p>${p.text}</p><button ${points<p.cost?'disabled':''}>${p.cost}P 교환</button>`;a.querySelector('button').onclick=()=>{if(points<p.cost)return;points-=p.cost;const v={name:p.name,code:`SEA-${Date.now().toString().slice(-8)}`,date:new Date().toLocaleDateString('ko-KR')};vouchers.unshift(v);save();$('#voucher-title').textContent=p.name;$('#voucher-description').textContent=`${p.cost}P를 사용해 쿠폰 보관함에 저장했습니다.`;$('#voucher-code').textContent=v.code;$('#voucher-dialog').showModal();renderRewards();};return a;}
function donationCard(d){const a=document.createElement('article');a.className='donation-card';a.innerHTML=`<h3>${d.name}</h3><p>${d.text}</p><button ${points<d.cost?'disabled':''}>${d.cost}P 기부 응원</button>`;a.querySelector('button').onclick=()=>{if(points<d.cost)return;points-=d.cost;donations.unshift({...d,date:Date.now()});save();$('#donation-title').textContent='해양 보전 응원 기록 완료';$('#donation-description').textContent=`${d.name}에 ${d.cost}P 응원 기록을 남겼습니다. 실제 기부는 공식 시스템 연동이 필요합니다.`;$('#donation-dialog').showModal();renderRewards();};return a;}
$('#collection-search').oninput=renderCollection;$('#collection-filter').onchange=renderCollection;
function renderCollection(){const found=new Set(catches.map(c=>c.fishId)), released=new Set(releases.map(r=>r.fishId)),q=$('#collection-search').value.trim(),filter=$('#collection-filter').value;$('#collection-count').textContent=`${found.size} / ${fishRules.length}`;$('#collection-percent').textContent=`${Math.round(found.size/fishRules.length*100)}%`;$('#collection-releases').textContent=`${releases.length}회`;const list=fishRules.filter(f=>(!q||f.name.includes(q))&&(filter==='all'||(filter==='found'&&found.has(f.id))||(filter==='released'&&released.has(f.id))));$('#fish-collection').replaceChildren(...list.map(f=>{const a=document.createElement('article');a.className='fish-card '+(found.has(f.id)?'':'locked');a.innerHTML=`<small>NO.${String(fishRules.indexOf(f)+1).padStart(3,'0')}</small><h3>${found.has(f.id)?f.name:'미발견 어종'}</h3><small>${found.has(f.id)?`예시 기준 ${f.minSize}cm`:'사진 분석 시 공개됩니다.'}</small>`;return a;}));}
function renderMyPage(){const found=new Set(catches.map(c=>c.fishId));$('#profile-name').value=profile.name||'';$('#profile-area').value=profile.area||'';$('#my-name').textContent=profile.name||'바다 지킴이';$('#my-summary').innerHTML=`<strong>포인트<br>${points}P</strong><strong>발견 기록<br>${catches.length}건</strong><strong>방생 기록<br>${releases.length}회</strong><strong>도감<br>${found.size}/${fishRules.length}</strong>`;const activity=[...catches.map(x=>({t:'어종 분석',d:x.date,f:x.fishId})),...releases.map(x=>({t:`방생 +${x.points}P`,d:x.date,f:x.fishId})),...vouchers.map(x=>({t:`쿠폰 교환 · ${x.name}`,d:Date.parse(x.date)||Date.now()}))].sort((a,b)=>b.d-a.d).slice(0,8);$('#activity-list').innerHTML=activity.length?activity.map(x=>`<p>• ${x.t}${x.f?` · ${fishRules.find(f=>f.id===x.f)?.name||''}`:''}<small> (${new Date(x.d).toLocaleDateString('ko-KR')})</small></p>`).join(''):'<p>아직 기록이 없습니다.</p>';}
$('#profile-save').onclick=()=>{profile={name:$('#profile-name').value.trim()||'바다 지킴이',area:$('#profile-area').value.trim()||'부산 연안'};save();renderMyPage();toast('이 기기에 프로필을 저장했습니다.');};
$('#gbif-check').onclick=async()=>{const out=$('#gbif-status');out.textContent='공개 관찰 메타데이터 연결을 확인하는 중…';try{const r=await fetch('https://api.gbif.org/v1/occurrence/search?country=KR&media_type=StillImage&limit=1');if(!r.ok)throw new Error();const d=await r.json();out.textContent=`연결됨 · 한국 이미지 관찰 메타데이터 ${Number(d.count||0).toLocaleString()}건을 조회할 수 있습니다. 자동 학습·사진 업로드는 하지 않습니다.`;}catch{out.textContent='현재 연결을 확인하지 못했습니다. 네트워크 상태를 확인해 주세요.';}};
renderHome();renderRewards();renderCollection();
